### ISSUE TITLE
ModuleNotFoundError: No module named 'Queue'

### ISSUE THREAD

**Issue by diogob003** [xiongyihui/pqcom#8]
```sh
→ pqcom python3 pqcom.py
Traceback (most recent call last):
  File "~/Library/Python/3.12/lib/python/site-packages/pqcom/./pqcom.py", line 41, in <module>
    import pqcom_serial
  File "~/Library/Python/3.12/lib/python/site-packages/pqcom/pqcom_serial.py", line 5, in <module>
    import Queue
ModuleNotFoundError: No module named 'Queue'
```
https://stackoverflow.com/questions/33432426/importerror-no-module-named-queue

**Comment by diogob003** [comment]
[README.md](/xiongyihui/pqcom/blob/master/README.md) instructions are contradictory
- Put `pip install pqcom` on instructions, but [pip pqcom package still on v0.5.2](https://pypi.org/project/pqcom/) that do not require `pyqt5` neither `pyside6` only `pyside`. And your last release is [v0.7.1](https://github.com/xiongyihui/pqcom/releases/tag/0.7.1) which is not on pip repo.
- Do not specify supported python version (pyqt5, PySide6 did not worked with python 3.12, only with python 3.11)
- List both `pyside6` and `pyqt5` on install instructions. However only `pyqt5` is required for v0.7.x. And only `pyside6` is required for latest `master branch` version.

The program only worked on mac after manually download and install python 3.11 and `pqcom-0.7.1-py3-none-any.whl`
```sh
sudo port install python311 py311-pip py311-pyqt5
cd ~/Downloads
python3.11 -m pip install ./pqcom-0.7.1-py3-none-any.whl pyserial pyqt5
python3.11 ~/Library/Python/3.11/bin/pqcom
```
